//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaKabul
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HastaKabul()
        {
            this.HastaHizmetHareketler = new HashSet<HastaHizmetHareketler>();
            this.HastaSikayetleri1 = new HashSet<HastaSikayetleri>();
            this.Odemeler = new HashSet<Odemeler>();
            this.Receteler = new HashSet<Receteler>();
            this.Tahliller = new HashSet<Tahliller>();
            this.Teshisler = new HashSet<Teshisler>();
        }
    
        public int KabulID { get; set; }
        public System.DateTime GelisTarihi { get; set; }
        public int HastaID { get; set; }
        public int PersonelID { get; set; }
        public int KlinikID { get; set; }
        public int SikayetID { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaHizmetHareketler> HastaHizmetHareketler { get; set; }
        public virtual Hastalar Hastalar { get; set; }
        public virtual HastaSikayetleri HastaSikayetleri { get; set; }
        public virtual Klinikler Klinikler { get; set; }
        public virtual Personeller Personeller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaSikayetleri> HastaSikayetleri1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odemeler> Odemeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receteler> Receteler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tahliller> Tahliller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teshisler> Teshisler { get; set; }
    }
}
