//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaHizmetHareketler
    {
        public int HareketID { get; set; }
        public System.DateTime Tarih { get; set; }
        public int KabulID { get; set; }
        public int TahlilSonucID { get; set; }
        public int HizmetID { get; set; }
        public decimal Tutar { get; set; }
        public string Aciklama { get; set; }
        public bool Silindi { get; set; }
    
        public virtual Hizmetler Hizmetler { get; set; }
        public virtual HastaTahlilSonuclari HastaTahlilSonuclari { get; set; }
        public virtual HastaKabul HastaKabul { get; set; }
    }
}
