//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hizmetler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hizmetler()
        {
            this.HastaHizmetHareketler = new HashSet<HastaHizmetHareketler>();
        }
    
        public int HizmetID { get; set; }
        public string HizmetAdi { get; set; }
        public int KlinikID { get; set; }
        public decimal Ucret { get; set; }
        public string Aciklama { get; set; }
        public bool Silindi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaHizmetHareketler> HastaHizmetHareketler { get; set; }
        public virtual Klinikler Klinikler { get; set; }
    }
}
