//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceteDetay
    {
        public int ReceteDetayID { get; set; }
        public int ReceteID { get; set; }
        public string İlacAd { get; set; }
        public string İlacKullanimSikligi { get; set; }
    
        public virtual Receteler Receteler { get; set; }
    }
}
