//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TahlilIcerik
    {
        public int TahlilIcerikId { get; set; }
        public string TahlilIcerikAdi { get; set; }
        public string TahlilIcerikReferansDegeri { get; set; }
        public string TahlilSonucBirimi { get; set; }
        public int TahlilId { get; set; }
        public string TahlilIcerikSonuc { get; set; }
    
        public virtual Tahliller Tahliller { get; set; }
    }
}
