//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teshisler
    {
        public int TeshisID { get; set; }
        public System.DateTime Tarih { get; set; }
        public int PersonelID { get; set; }
        public int KabulID { get; set; }
        public string Teshis { get; set; }
    
        public virtual HastaKabul HastaKabul { get; set; }
        public virtual Personeller Personeller { get; set; }
    }
}
